name: Geo-joinery setup
description: Initialize a new joinery by creating joinery.toml
inputs:
  name:
    description: The name of the joinery
    required: true
runs:
  using: composite
  steps:
    - name: Create joinery config
      shell: bash
      run: |
        cat > joinery.toml << EOF
        [geo-joinery]
        name = "${{ inputs.joinery-name }}"
        EOF
    - name: Commit config
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add joinery.toml
        git commit -m "chore: initialize joinery.toml"
        git push
