name: Geo-joinery setup
description: Initialize a new geo-joinery in a GitHub hosted repository.
inputs:
  name:
    description: The name of the joinery
    required: true
runs:
  using: composite
  steps:
    - name: Write npm package configuration
      shell: bash
      run: |
        cp "${{ github.action_path }}/package.json" .
        npm install
        git add package.json package-lock.json
    - name: Write update website workflow
      shell: bash
      env:
        REPOSITORY_NAME: ${{ github.event.repository.name }}
      run: |
        envsubst < "${{ github.action_path }}/update-website.yml" > .github/workflows/update-website.yml
        git add .github/workflows/update-website.yml
    - name: Write MyST configuration
      shell: bash
      run: |
        npx myst init --config docs/myst.yml
        git add docs/myst.yml
    - name: Write geo-joinery configuration
      shell: bash
      env:
        PROJECT_NAME: ${{ inputs.name }}
      run: |
        envsubst < "${{ github.action_path }}/geo-joinery.toml" > geo-joinery.toml
        git add geo-joinery.toml
    - name: Commit configuration files
      shell: bash
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git commit -m "chore: initial setup"
        git push
