name: Geo-joinery processing
description: (Re)produce data processing steps as needed
runs:
  using: composite
  steps:
    - name: Set UV_PROJECT
      shell: bash
      run: echo "UV_PROJECT=${{ github.action_path }}/../../../" >> $GITHUB_ENV
    - name: Setup python
      uses: actions/setup-python@v6
      with:
        python-version-file: ${{ env.UV_PROJECT }}/pyproject.toml"
    - name: Install uv
      uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
      with:
        enable-cache: true
    - name: Install gejo-core
      shell: bash
      run: uv sync --locked
    - name: Call gejo-core
      shell: bash
      run: uv run python -c "import gejo_core;exit(gejo_core.reproduce())"
